routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'DashboardController@login')->name('dashboard.login');
Route::get('/dashboard', 'DashboardController@index')->name('dashboard.index');
Route::resource('/barang', 'BarangController');
Route::resource('/karyawan', 'KaryawanController');
Route::resource('/supplier', 'SupplierController');
Route::name('pemakaian.')->prefix('pemakaian')->group(function(){
    Route::get('/', 'PengeluaranController@index')->name('index');
});
Route::name('pemasukan.')->prefix('pemasukan')->group(function(){
    Route::get('/', 'PemasukanController@index')->name('index');
});
Route::name('laporan.')->prefix('laporan')->group(function(){
    Route::get('/barang', 'LaporanController@barang')->name('barang');
    Route::get('/cetakbarang', 'LaporanController@cetakbarang')->name('cetakbarang');
});
// Route::resource('/pemasukan')->prefix('pemasukan')->name('pemasukan')

app/Http/Controllers/LaporanController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Barang;
use PDF;

class LaporanController extends Controller
{
    public function barang()
    {
        $data = Barang::all();
        return view('laporan.barang', compact('data'));
    }
    public function cetakbarang()
    {
    	$data = Barang::all();
 
    	$pdf = PDF::loadview('laporan.barang_pdf',['data'=>$data]);
    	return $pdf->download('laporan-barang.pdf');
    }
}

resources/views/laporan/barang.blade.php
@extends('layout.main')
@section('title', 'Laporan Barang - SI Pemakaian ATK')
@section('content')
<div class="row">
    <div class="col-sm-4">
        <!-- general form elements -->
        <div class="card card-primary">
            <div class="card-header">
                <h3 class="card-title">Data Filter</h3>
            </div>
            <form role="form">
                <div class="card-body">
                    <div class="form-group">
                        <label>Filter Tanggal Dari - Sampai</label>
                        <div class="input-group">
                            <div class="input-group-prepend">
                              <span class="input-group-text">
                                <i class="far fa-calendar-alt"></i>
                              </span>
                            </div>
                            <input type="text" class="form-control float-right" id="reservation">
                          </div>
                    </div>
                </div>
            </form>
            <div class="card-footer">
                <button class="btn btn-success">Filter Data</button>
                <a href="{{route('laporan.cetakbarang')}}" target="_blank" class="btn btn-primary">Cetak Data (PDF)</a>
            </div>
        </div>
    </div>
    <div class="col-sm-8">
        <div class="card card-default">
            <div class="card-header">
                <h3 class="card-title">Data Barang</h3>
            </div>
            <div class="card-body">
                <table id="example2" class="table table-bordered table-striped">
                   <thead>
                       <tr>
                           <td>Nama ATK</td>
                           <td>Satuan</td>
                           <td>Jumlah</td>
                       </tr>
                   </thead>
                   <tbody>
                       @foreach ($data as $barang)
                           <tr>
                                <td>{{$barang->nama_atk}}</td>
                                <td>{{$barang->satuan}}</td>
                                <td>{{$barang->jumlah}}</td>
                           </tr>
                       @endforeach
                   </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection
@section('costumjs')
<!-- date-range-picker -->
<script src="{{asset('plugins/daterangepicker/daterangepicker.js')}}"></script>
<script>
    $(function () {
        $('#reservation').daterangepicker()

        $('#example2').DataTable({
            "paging": true,
            "lengthChange": false,
            "searching": false,
            "ordering": true,
            "info": true,
            "autoWidth": false,
        });
    });

</script>
@endsection

resources/views/laporan/barang_pdf.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>Laporan Data Barang</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
	<style type="text/css">
		table tr td,
		table tr th{
			font-size: 9pt;
		}
	</style>
	<center>
		<h5>Laporan Data Barang</h4>
	</center>

	<table class='table table-bordered'>
		<thead>
			<tr>
				<th>No</th>
				<th>Nama ATK</th>
				<th>Jumlah</th>
                <th>Satuan</th>
			</tr>
		</thead>
		<tbody>
			@php $i=1 @endphp
			@foreach($data as $p)
			<tr>
				<td>{{ $i++ }}</td>
				<td>{{$p->nama_atk}}</td>
				<td>{{$p->jumlah}}</td>
                <td>{{$p->satuan}}</td>
			</tr>
			@endforeach
		</tbody>
	</table>
</body>
</html>